# Generated by Django 5.1.15 on 2026-04-30 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('region_type', models.CharField(choices=[('city', 'Shahar'), ('district', 'Tuman')], default='district', max_length=10, verbose_name='Turi')),
                ('latitude', models.FloatField(verbose_name='Kenglik (latitude)')),
                ('longitude', models.FloatField(verbose_name='Uzunlik (longitude)')),
                ('population', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aholi soni')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar (tumanlar)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dorixona nomi')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('latitude', models.FloatField(verbose_name='Kenglik')),
                ('longitude', models.FloatField(verbose_name='Uzunlik')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name="Qo'shimcha telefon")),
                ('working_hours', models.CharField(default='09:00 - 21:00', max_length=100, verbose_name='Ish vaqti')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24/7 ishlaydi')),
                ('has_delivery', models.BooleanField(default=False, verbose_name='Yetkazib berish bor')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to='pharmacies.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Dorixona',
                'verbose_name_plural': 'Dorixonalar',
                'ordering': ['-is_verified', 'name'],
                'indexes': [models.Index(fields=['region', 'is_active'], name='pharmacies__region__ab4625_idx'), models.Index(fields=['latitude', 'longitude'], name='pharmacies__latitud_79a150_idx')],
            },
        ),
    ]
