# Generated by Django 5.1.15 on 2026-04-30 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, verbose_name="Qidiruv so'rovi")),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Topilgan natijalar')),
                ('user_lat', models.FloatField(blank=True, null=True, verbose_name='Foydalanuvchi kengligi')),
                ('user_lng', models.FloatField(blank=True, null=True, verbose_name='Foydalanuvchi uzunligi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Qidirilgan vaqt')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacies.region', verbose_name='Hudud')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Qidiruv tarixi',
                'verbose_name_plural': 'Qidiruv tarixi',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['query', '-searched_at'], name='search_sear_query_3dafff_idx')],
            },
        ),
    ]
