# Generated by Django 5.1.15 on 2026-04-30 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, default='fa-pills', max_length=50, verbose_name='Icon (FontAwesome class)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='medicines.medicinecategory', verbose_name='Asosiy turkum')),
            ],
            options={
                'verbose_name': 'Dori turkumi',
                'verbose_name_plural': 'Dori turkumlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tijorat nomi')),
                ('generic_name', models.CharField(blank=True, max_length=200, verbose_name='Xalqaro nomi (INN)')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Ishlab chiqaruvchi')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Mamlakat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('indications', models.TextField(blank=True, verbose_name="Foydalanish ko'rsatmalari")),
                ('contraindications', models.TextField(blank=True, verbose_name="Qarshi ko'rsatmalar")),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tabletka'), ('capsule', 'Kapsula'), ('syrup', 'Sirop'), ('injection', 'Inyeksiya / Ampula'), ('cream', 'Krem / Maz'), ('drops', 'Tomchi'), ('powder', 'Kukun'), ('spray', 'Sprey'), ('other', 'Boshqa')], default='tablet', max_length=20, verbose_name='Shakli')),
                ('dosage', models.CharField(blank=True, help_text='Masalan: 500 mg, 100 ml', max_length=100, verbose_name='Dozasi')),
                ('prescription_required', models.BooleanField(default=False, verbose_name='Retsept talab qilinadi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicines/', verbose_name='Rasm')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Shtrix-kod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.medicinecategory', verbose_name='Turkum')),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Narx (so'm)")),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Miqdori')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='medicines.medicine', verbose_name='Dori')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='pharmacies.pharmacy', verbose_name='Dorixona')),
            ],
            options={
                'verbose_name': 'Dorixona zaxirasi',
                'verbose_name_plural': 'Dorixona zaxiralari',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medicines_m_name_61a774_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='medicines_m_generic_1e9386_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystock',
            index=models.Index(fields=['pharmacy', 'is_available'], name='medicines_p_pharmac_91071e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystock',
            index=models.Index(fields=['medicine', 'is_available'], name='medicines_p_medicin_a558b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacystock',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
